name: CI
on:
  push:
    branches:
      - maint-3.8
  pull_request:
    branches:
      - maint-3.8

jobs:
  ubuntu-20-04:
    name: GNURadio on Ubuntu 20.04
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install GNURadio
        run: |
         sudo apt update
         sudo apt install gnuradio-dev
         sudo apt install cmake liborc-0.4-dev
      - name: Build
        run: |
         cmake -B build
         cmake --build build
      - name: Install
        run: |
         cd build
         sudo make install
         export PYTHONPATH=/usr/local/lib/python3/dist-packages
         sudo ldconfig
      - name: Demod PRBS15
        run: |
         export PYTHONPATH=/usr/local/lib/python3/dist-packages
         iridium-extractor --offline -c 1622000000 -r 2000000 -f float test-data/prbs15-2M-20dB.fc32 > prbs15-2M-20dB.bits
         cat prbs15-2M-20dB.bits | grep 0011000000110000111100111000000000000011000000000000101000000000001111000000000010001000000000110011000000001010101000000011111111000000100000001000001100000011000010100000101000111100001111001000100010001011001100110011101010101010100111111111111101000000000000111000000000001001000000000011011000000000101101000000001110111000000010011001000000110101011000001011111101000011100000
